FROM golang:1.25.2 AS build

WORKDIR /build

COPY go.mod .
COPY go.mod .

RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o ./app ./cmd

FROM alpine:latest

WORKDIR /app

COPY --from=build /build/app .

EXPOSE 8000

CMD ["/app/app"]